# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2015
build: off

# Test against these versions of Io.js and Node.js.
environment:
  matrix:
    - arch: x86_64
      bits: 64
      nodejs_version: 9
    - arch: i686
      bits: 32
      nodejs_version: 9

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - npm install

test_script:
  - node --version
  - npm --version
  #- npm test

# Set build version format here instead of in the admin panel.
version: "{build}"